//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAS Calibration.
        /// </summary>
        public static string BAS_Calibration {
            get {
                return ResourceManager.GetString("BAS_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application may be not working, please close app and try again.
        /// </summary>
        public static string CheckTimer_Content {
            get {
                return ResourceManager.GetString("CheckTimer_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect with server.
        /// </summary>
        public static string CheckTimer_Title {
            get {
                return ResourceManager.GetString("CheckTimer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear DTC.
        /// </summary>
        public static string Clear_DTC {
            get {
                return ResourceManager.GetString("Clear_DTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect device first.
        /// </summary>
        public static string Connect_Required {
            get {
                return ResourceManager.GetString("Connect_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected.
        /// </summary>
        public static string Connect_Title {
            get {
                return ResourceManager.GetString("Connect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect device.
        /// </summary>
        public static string ConnectFail_Title {
            get {
                return ResourceManager.GetString("ConnectFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Flow.
        /// </summary>
        public static string Data_Flow {
            get {
                return ResourceManager.GetString("Data_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device disconnected.
        /// </summary>
        public static string Disconnect_Title {
            get {
                return ResourceManager.GetString("Disconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update package failed.
        /// </summary>
        public static string Download_Package_Fail {
            get {
                return ResourceManager.GetString("Download_Package_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC Info.
        /// </summary>
        public static string DTC_Info {
            get {
                return ResourceManager.GetString("DTC_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU Info.
        /// </summary>
        public static string ECU_Info {
            get {
                return ResourceManager.GetString("ECU_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU not responded.
        /// </summary>
        public static string ECU_not_resp {
            get {
                return ResourceManager.GetString("ECU_not_resp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU with DTC.
        /// </summary>
        public static string ECU_with_DTC {
            get {
                return ResourceManager.GetString("ECU_with_DTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECU without DTC.
        /// </summary>
        public static string ECU_without_DTC {
            get {
                return ResourceManager.GetString("ECU_without_DTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Type.
        /// </summary>
        public static string Failure_Type {
            get {
                return ResourceManager.GetString("Failure_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Vehicle.
        /// </summary>
        public static string Flash_Vehicle {
            get {
                return ResourceManager.GetString("Flash_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get access from server.
        /// </summary>
        public static string Get_Access_Fail {
            get {
                return ResourceManager.GetString("Get_Access_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get latest FRS from server.
        /// </summary>
        public static string Get_FRS_Fail {
            get {
                return ResourceManager.GetString("Get_FRS_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get latest VDSA version.
        /// </summary>
        public static string Get_Latest_VDSA_Fail {
            get {
                return ResourceManager.GetString("Get_Latest_VDSA_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get vehicle information from server.
        /// </summary>
        public static string Get_Veh_Info_Fail {
            get {
                return ResourceManager.GetString("Get_Veh_Info_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string Health_Check {
            get {
                return ResourceManager.GetString("Health_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HV Battery Health Report.
        /// </summary>
        public static string HV_Battery_Health_Report {
            get {
                return ResourceManager.GetString("HV_Battery_Health_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immobiliser.
        /// </summary>
        public static string Immobiliser {
            get {
                return ResourceManager.GetString("Immobiliser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to install it now.
        /// </summary>
        public static string Install_Required {
            get {
                return ResourceManager.GetString("Install_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Control.
        /// </summary>
        public static string IO_Control {
            get {
                return ResourceManager.GetString("IO_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Provision Data.
        /// </summary>
        public static string Lock_Provision {
            get {
                return ResourceManager.GetString("Lock_Provision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login again to use application, do you want to continue?.
        /// </summary>
        public static string Logout_Content {
            get {
                return ResourceManager.GetString("Logout_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Logout_Title {
            get {
                return ResourceManager.GetString("Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHU Recovery Mode.
        /// </summary>
        public static string MHU_Recovery_Mode {
            get {
                return ResourceManager.GetString("MHU_Recovery_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing database of.
        /// </summary>
        public static string Miss_Data {
            get {
                return ResourceManager.GetString("Miss_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.
        /// </summary>
        public static string New_Ver_Available {
            get {
                return ResourceManager.GetString("New_Ver_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No_Header {
            get {
                return ResourceManager.GetString("No_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found VDSA update tool.
        /// </summary>
        public static string Not_Found_Update_Tool {
            get {
                return ResourceManager.GetString("Not_Found_Update_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report to our support team.
        /// </summary>
        public static string Please_Report {
            get {
                return ResourceManager.GetString("Please_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software update process is to upgrade the ECU&apos;s software to the latest version.
        /// </summary>
        public static string Programming_Desc {
            get {
                return ResourceManager.GetString("Programming_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not interact with the screen under any circumstances while the application is running.
        /// </summary>
        public static string Programming_MHU_MainReq {
            get {
                return ResourceManager.GetString("Programming_MHU_MainReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect the ECU to the computer using a USB cable.
        /// </summary>
        public static string Programming_MHU_req {
            get {
                return ResourceManager.GetString("Programming_MHU_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that the computer is connected to a 12V power supply, has sufficient power, and is not shut down or locked during the software update process.
        ///The vehicle must be maintained at 12V and remain stationary in Park (P) mode.
        /// </summary>
        public static string Programming_Req {
            get {
                return ResourceManager.GetString("Programming_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision.
        /// </summary>
        public static string Provision {
            get {
                return ResourceManager.GetString("Provision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read CDS Coding.
        /// </summary>
        public static string Read_CDS_Coding {
            get {
                return ResourceManager.GetString("Read_CDS_Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read VIN.
        /// </summary>
        public static string Read_VIN {
            get {
                return ResourceManager.GetString("Read_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read VOD Coding.
        /// </summary>
        public static string Read_VOD_Coding {
            get {
                return ResourceManager.GetString("Read_VOD_Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading VIN.
        /// </summary>
        public static string Reading_VIN {
            get {
                return ResourceManager.GetString("Reading_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement.
        /// </summary>
        public static string Requirement {
            get {
                return ResourceManager.GetString("Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAS Calibration.
        /// </summary>
        public static string SAS_Calibration {
            get {
                return ResourceManager.GetString("SAS_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report.
        /// </summary>
        public static string Save_Report {
            get {
                return ResourceManager.GetString("Save_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect vehicle to see ECU topology.
        /// </summary>
        public static string See_ECU_topology {
            get {
                return ResourceManager.GetString("See_ECU_topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        public static string Select_device {
            get {
                return ResourceManager.GetString("Select_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select model first.
        /// </summary>
        public static string Select_Model_Required {
            get {
                return ResourceManager.GetString("Select_Model_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select device port.
        /// </summary>
        public static string Select_Title {
            get {
                return ResourceManager.GetString("Select_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPMS ID (read and write).
        /// </summary>
        public static string TPMS_ID {
            get {
                return ResourceManager.GetString("TPMS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will update automatically after closing.
        /// </summary>
        public static string Update_Automatic {
            get {
                return ResourceManager.GetString("Update_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Fail.
        /// </summary>
        public static string Update_Fail {
            get {
                return ResourceManager.GetString("Update_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string User_Department {
            get {
                return ResourceManager.GetString("User_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Infomation.
        /// </summary>
        public static string User_Information {
            get {
                return ResourceManager.GetString("User_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle DTC.
        /// </summary>
        public static string Vehicle_DTC {
            get {
                return ResourceManager.GetString("Vehicle_DTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter the expected Vincode.
        /// </summary>
        public static string Vincode_Miss_Match_Content {
            get {
                return ResourceManager.GetString("Vincode_Miss_Match_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VinCode miss match between MHU and BCM.
        /// </summary>
        public static string Vincode_Miss_Match_Title {
            get {
                return ResourceManager.GetString("Vincode_Miss_Match_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write CDS Coding.
        /// </summary>
        public static string Write_CDS_Coding {
            get {
                return ResourceManager.GetString("Write_CDS_Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write FRS Number.
        /// </summary>
        public static string Write_FRS_Number {
            get {
                return ResourceManager.GetString("Write_FRS_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Hardware.
        /// </summary>
        public static string Write_Hardware {
            get {
                return ResourceManager.GetString("Write_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write VIN.
        /// </summary>
        public static string Write_VIN {
            get {
                return ResourceManager.GetString("Write_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write VOD Coding.
        /// </summary>
        public static string Write_VOD_Coding {
            get {
                return ResourceManager.GetString("Write_VOD_Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to get latest FRS from server.
        /// </summary>
        public static string WriteFRS_Step1_Fail {
            get {
                return ResourceManager.GetString("WriteFRS_Step1_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest FRS have been got from server.
        /// </summary>
        public static string WriteFRS_Step1_Pass {
            get {
                return ResourceManager.GetString("WriteFRS_Step1_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to write FRS number.
        /// </summary>
        public static string WriteFRS_Step2_Fail {
            get {
                return ResourceManager.GetString("WriteFRS_Step2_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write FRS Number complete.
        /// </summary>
        public static string WriteFRS_Step2_Pass {
            get {
                return ResourceManager.GetString("WriteFRS_Step2_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing FRS number.
        /// </summary>
        public static string WriteFRS_Step2_Running {
            get {
                return ResourceManager.GetString("WriteFRS_Step2_Running", resourceCulture);
            }
        }
    }
}
